[package]
name = "approval-receiver"
version = "0.0.1"
authors = ["Octopus Network"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { version = "4.0.0" }
near-contract-standards = { version = "4.0.0" }
