[package]
name = "wrapped-appchain-nft"
version = "1.0.0"
authors = ["Octopus Network"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { version = "4.0.0" }
near-contract-standards = { version = "4.0.0" }
